- test/StyleSheet.js
I seem to have found a bug when calling `toString` on style sheets with media queries.
I'm not sure yet how to fix this, but I figured I'd open a discussion by providing a failing test.
The current failing test case shows how this:
```js
{a: {color: 'red'}, '@media (min-width: 1024px)': {a: {color: 'blue'}}}
```
is erroneously compiled into this:
```css
.jss-0 {
color: red;
}
.jss-1 {
a: [object Object];
}
```
> Add failing test for 'toString' on media queries

- lib/StyleSheet.js
Without this, there is no way to get the `classNames` that are related ONLY to the rules that have been currently added (with `addRules()`). This is different from `styleSheet.rules` , which stores ALL current rules.
A use case is when we need the `classNames` of some added rules, while rendering on the server. Maybe there is a need to add rules of all components in a tree, to the same global StyleSheet instance. That instance will be created on each request. We need `classNames` of each component, before calling `styleSheet.toString()` at the final step, when all rules have been added and the complete tree has been rendered. In that case we have to get the `classNames` from the returned values of `addRule()/addRules()`.
> Return added rules from styleSheet.addRules()

- src/Jss.js
- test/Rule.js
This allows you to use the `use` method like so:
```js
jss.use(extend(), nested(), defaultUnit());
```
> Make the `use` method variadic.

- docs/benefits.md
- docs/js-api.md
- docs/json-api.md
Minor tweaks to docs.
benefits.md
+ explicitely => explicitly
+ netsted => nested
+ repeatitions => repetitions
+ standartized => standardized
js-api.md
+ Usefull => Useful
+ unsused => unused
json-api.md
+ carefull => careful
Feel free to correct me if I made mistake to words :)
> Fixes typos in docs

- src/StyleSheet.js
- tests/integration/sheet.js
Implements #180
I wanted to add a test for this, but looks like with the current test setup it is hard to verify the scenario, because `jss.generateClassName()` always generates class names with the same suffix: https://github.com/jsstyles/jss/blob/master/tests/utils.js#L44 . Please let me know if you'd like to still have a test for it and advise how to overcome the aforementioned issue.
> Media queries and other conditional selectors before the rules they overwrite

- src/backends/DomRenderer.js
`jss` would definitely benefit from a better test suite, would help avoid little things like this typo 👍 
If we end up using `jss` I can certainly help with that!
> Fix typo in dom renderer

- docs/js-api.md
- docs/setup.md
- src/SheetsRegistry.js
- src/StyleSheet.js
- src/backends/DomRenderer.js
- tests/functional/priority.js
- tests/functional/sheet.js
- tests/integration/priority.js
- tests/utils.js
ref #290
@kof Once you have 👍 the implementation I will document the feature.
Please review and let me know anything you'd like to see changed.
When using the priority/index feature there's some extra array iteration when adding and attaching sheets. One could use a binary search but I don't think it would make a real difference with the length of the registry array in typical usage.
This should give you a good handle on the usage -> output: https://github.com/nathanmarks/jss/blob/priority/tests/integration/priority.js
> Add DOM priority feature via index option

- package.json
- src/StyleSheet.js
- src/backends/DomRenderer.js
- tests/functional/sheet.js
- tests/utils.js
Fixes #318
When sheet is attached and deployed and `.addRule`:
- is used from a plugin, order is not preserved
- at-rules are not inserted using `insertRule` api in IE
> fix addRule insertion order from plugins, fix @media insertion

- src/plugins/RegularRule.js
- src/utils/generateClassName.js
- tests/integration/sheet.js
Follow up to #350 .
From #374 
>  it is possible that 2 equal rules exist in 2 different sheets rendered at different times. Class name generation uses rules style object at the moment.
Addresses this by including the sheet meta (if provided) in the string that gets hashed.
@kof
> Add sheet meta value to className hash

- .npmignore
- package.json
That’s what you publish to npm now:
Most of this files aren‘t necessary. I’m not sure about flow files though.
> Use files field in package.json instead of .npmignore

- docs/json-api.md
- readme.md
Just a small modification on the docs. As of https://github.com/Qix-/color/pull/96 the method for converting to a hex string is now just `.hex()`.
> Renamed method call from '.hexString()' to the new '.hex()'.

- src/utils/toCss.js
- tests/functional/sheet.js
The problem is that `rule.toString()` returns nothing if we have just function values in rule without calculated values. So it needs to return just an empty rule like `.class {}` to be applied to the stylesheet.
> Fix addRule for functional values, fix #475

- src/Jss.js
- src/types.js
#495 If `options` is optional, it must have the default value. In our case it is empty object. But the empty object is incompatible with `StyleSheetOptions` since `StyleSheetOptions` has a required parameter `jss`. But since the `StyleSheet` constructor still comes with an object with this parameter, we do not need to make it required in the `createStyleSheet` options. To solve the problem, I created `StyleSheetFactoryOptions` type.
> Fix createStyleSheet type definitions error

- flow-typed/cssom.js
There are some hacks:
- we need to use generic type, because there is no override for extended interfaces
- we need to use hacks like `1|1` because it looks like flow casts `$PropertyType<T, prop>` for constant numbers into type `number` (invokes `typeof`?)
> Fix CSSOM types

- src/SheetsManager.js
The warn function had a missing argument and didn't output the passed in the message but instead threw an error because it was missing an argument
It would throw [this](https://github.com/BerkeleyTrue/warning/blob/master/warning.js#L31)
> Fixed warning in sheets manager

- src/types.js
Environment:
node 7.10.1
jss 8.1.0
flow-bin: 0.55.0
In `types.js`, interface `Renderer` declares a constructor function with return type `Renderer`. However, constructor functions should have return type `void` as far as I know. Otherwise I get a bunch of flow issues:
```
Error: node_modules/jss/lib/types.js.flow:25
25:   constructor(sheet?: StyleSheet): Renderer;
^^^^^^^^ property `attach` of Renderer. Property not found in possibly undefined value
205:   constructor(sheet?: StyleSheet) {
^ undefined. See: node_modules/jss/lib/renderers/DomRenderer.js.flow:205
Error: node_modules/jss/lib/types.js.flow:25
25:   constructor(sheet?: StyleSheet): Renderer;
^^^^^^^^ property `attach` of Renderer. Property not found in possibly undefined value
7: export default class VirtualRenderer { …
```
> fix: constructor-function declaration should have return type `void`

- src/plugins/observables.js
- src/types.js
- src/utils/cloneStyle.js
- tests/functional/observables.js
I've started writing a plugin that adds support for Observable rules (#607).  Right now, I'm seeing this warning:
```
Rule is not linked. Missing sheet option "link: true".
```
Even though `{ link: true }` is clearly specified in the tests.
> WIP add support for Observable rules

- readme.md
Material UI alpha was released.
P.S: The https://github.com/callemall/material-ui/tree/v1-alpha link is broken.
Current Material UI version: https://github.com/callemall/material-ui/releases/tag/v1.0.0-beta.19
> Cross off releasing material-ui alpha from roadmap

- docs/js-api.md
It was missing the "new" operator.
> Fix SheetsManager example in documentation

- packages/jss-plugin-syntax-rule-value-function/src/function-rules.test.js
- packages/jss-plugin-syntax-rule-value-function/src/function-values.test.js
- packages/jss-plugin-syntax-rule-value-function/src/index.test.js
- packages/jss-plugin-syntax-rule-value-observable/src/observable.test.js
I removed the DOM tests from the function and observable plugins because updating the DOM isn't done in those packages.
We could extract some testing utils into a private package, for example, the `createGenerateClassName` is being used in every package.
> Removed DOM tests from function and observable plugin

- packages/jss-plugin-syntax-compose/.size-snapshot.json
- packages/jss-plugin-syntax-extend/.size-snapshot.json
- packages/jss-plugin-syntax-global/.size-snapshot.json
- packages/jss-plugin-syntax-nested/.size-snapshot.json
- packages/jss-plugin-syntax-nested/package-lock.json
- packages/jss-plugin-syntax-rule-value-function/.size-snapshot.json
- packages/jss-plugin-syntax-rule-value-function/src/index.js
- packages/jss-plugin-syntax-rule-value-observable/.size-snapshot.json
- packages/jss-plugin-syntax-rule-value-observable/src/index.js
- packages/jss-plugin-syntax-template/.size-snapshot.json
- packages/jss-plugin-vendor-prefixer/.size-snapshot.json
- packages/jss-preset-default/.size-snapshot.json
- packages/jss/.size-snapshot.json
- packages/jss/package-lock.json
- packages/jss/src/index.js
- rollup.config.js
In this diff I refactored rollup config in favor of composition
instead of mixins.
- made createRule part of a public api; this allows to get rid from
interals usage in plugins
- peer dependencies are global in umd; this reduces plugins
size significantly
- changed development back to production mode in umd.min
> UMD distribution fixes

- packages/jss/src/index.js
> Added exporting types from jss

- packages/jss-plugin-cache/src/index.js
- packages/jss/src/types/jss.js
@kof could it be that the `RuleOptions` is missing the `parent` property because we are accessing it in the plugin. That's also why the CI is failing.
> Added typing to the cache plugin

- packages/jss-plugin-isolate/.size-snapshot.json
- packages/jss-plugin-isolate/src/index.js
- packages/jss-plugin-syntax-rule-value-function/.size-snapshot.json
- packages/jss-plugin-syntax-rule-value-function/src/index.js
- packages/jss-plugin-syntax-rule-value-observable/src/index.js
- packages/jss/src/index.js
- packages/jss/src/types/jss.js
Same problem with the `RuleOptions` as in #779.
Also, I'm importing the type of the StyleRule from the src. We should maybe export the Rules as well as they are needed for better typing in some of the plugins.
> Added typing to the isolate plugin

- packages/jss-plugin-syntax-camel-case/src/index.js
- packages/jss/src/types/jss.js
Updated the type definition of the onChangeValue function inside Plugins, because we call the onChangeValue only in the StyleRule.
> Added typings to the camel case plugin

- packages/jss-plugin-syntax-extend/src/index.js
- packages/jss/src/rules/StyleRule.js
- packages/jss/src/types/jss.js
Fixed typing of the `prop` method in `StyleRule` to allow null and false as values
> Added typing to expand plugin

- packages/jss-plugin-syntax-default-unit/src/index.js
- packages/jss-preset-default/src/index.js
I had to manually export and import the options because Flow doesn't seem to know how to extract function parameters sadly.
> Added typing to jss-preset-default

- packages/jss-plugin-syntax-compose/readme.md
- packages/jss-plugin-syntax-extend/.size-snapshot.json
- packages/jss-preset-default/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
For some reason, the snapshot files got out of date, and prettier didn't rewrite a markdown file.
> Fix snapshot sizes and run prettier

- packages/jss/.size-snapshot.json
- packages/jss/src/renderers/DomRenderer.js
- packages/jss/tests/functional/priority.js
- packages/react-jss/.size-snapshot.json
Fixes the sheet ordering as described in #816 
`prevNode` returns now an object because `nextSibling` may return null when it's the last element which results in not being able to get the parent for the insertion.
> Fixes sheet ordering

- .eslintrc
- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/JssProvider.test.js
- packages/react-jss/src/createHoc.js
- packages/react-jss/src/injectSheet.test.js
Addressing #802 
I had removed (almost) all of the usage of old lifecycle methods. I had not removed the `componentWillReceiveProps` because it is currently used for `context`, hence I also skipped the new `StrictMode` test.
For eslint, I had turned off `react/no-did-mount-set-state` and `react/no-did-update-set-state` (as written in [React's blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change)):
> Sometimes people use componentWillUpdate out of a misplaced fear that by the time componentDidUpdate fires, it is “too late” to update the state of other components. This is not the case. React ensures that any setState calls that happen during componentDidMount and componentDidUpdate are flushed before the user sees the updated …
> react-jss: Remove usage of deprecated lifecycle methods (#802)

- packages/react-jss/package.json
__What would you like to add/fix?__ Drop react 0.13 to eventually switch to the new context API polyfill.
__Corresponding issue (if exists):__ #836
> [react-jss] Drop React 0.13

- packages/react-jss/readme.md
Also removed the CI badge which is linked to the old builds
> Remove docs on forwardRef support in react-jss

- packages/react-jss/package.json
__What would you like to add/fix?__ Drop React 14 support
> [react-jss] Drop React 14

- changelog.md
- packages/jss-plugin-syntax-global/.size-snapshot.json
- packages/jss-plugin-syntax-global/src/index.js
- packages/jss-plugin-syntax-global/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
> Ignore undefine, null, or empty value rules when generate style.

- packages/jss/package.json
closes #881
I don't know what JSS is (it was installed as a dep of another dep in a project I'm maintaining), but this message shows up in the logs of my CI for every single run and it's getting annoying.
> remove nag message from postinstall script

- packages/react-jss/.size-snapshot.json
- packages/react-jss/package.json
- yarn.lock
- hoisting of new react features
cssinjs/react-jss#314
> `hoist-non-react-statics@2.x` does not support `forwardRef` components, `contextType` static nor `getDerivedStateFromError` static. The major version bump was due to the added requirement of react >= 0.14 which was dropped in `hoist-non-react-statics@3.2.0`. Therefore this change should not be breaking.
> 
> [`hoist-non-react-statics` changelog](https://github.com/mridgway/hoist-non-react-statics/blob/master/CHANGELOG.md)
> Fix hoisting of new react features

- packages/jss/benchmark/tests/create-instance.js
Add a benchmark for creating new jss instances. Once without any plugins and once with the preset.
Results:
Chrome 70.0.3538 (Mac OS X 10.14.2)  create a new instance with and without preset: without preset at 205906 ops/sec
Chrome 70.0.3538 (Mac OS X 10.14.2)  create a new instance with and without preset: with preset at 51269 ops/sec
> [jss] Add a benchmark for creating jss instances

- packages/react-jss/src/createHoc.js
Because we now only support react 16.3 or higher, we can safely add forward ref support again as also react redux has fixed their issue with the API.
__Corresponding issue:__ #800
> [react-jss] Add forward ref support

- package.json
- packages/jss-plugin-cache/package.json
- packages/jss-plugin-camel-case/package.json
- packages/jss-plugin-compose/package.json
- packages/jss-plugin-default-unit/package.json
- packages/jss-plugin-expand/package.json
- packages/jss-plugin-extend/package.json
- packages/jss-plugin-global/package.json
- packages/jss-plugin-isolate/package.json
- packages/jss-plugin-nested/package.json
- packages/jss-plugin-props-sort/package.json
- packages/jss-plugin-rule-value-function/package.json
- packages/jss-plugin-rule-value-observable/package.json
- packages/jss-plugin-template/package.json
- packages/jss-plugin-vendor-prefixer/package.json
- packages/jss-preset-default/package.json
This updates the peer dependencies to reflect the current dev dependencies.
> [core] Fix peer deps warnings

- lerna.json
- package.json
- packages/jss-plugin-cache/package.json
- packages/jss-plugin-camel-case/package.json
- packages/jss-plugin-compose/package.json
- packages/jss-plugin-default-unit/package.json
- packages/jss-plugin-expand/package.json
- packages/jss-plugin-extend/package.json
- packages/jss-plugin-global/package.json
- packages/jss-plugin-isolate/package.json
- packages/jss-plugin-nested/package.json
- packages/jss-plugin-props-sort/package.json
- packages/jss-plugin-rule-value-function/package.json
- packages/jss-plugin-rule-value-observable/package.json
- packages/jss-plugin-template/package.json
- packages/jss-plugin-vendor-prefixer/package.json
- packages/jss-preset-default/package.json
- packages/jss-starter-kit/package.json
- packages/jss/package.json
- packages/react-jss/package.json
- yarn.lock
This updates lerna to the newest version and moves all of the `build` scripts to `prepare`.
> [core] Update lerna

- yarn.lock
Field was added in `yarn@1.1.0`.
See yarnpkg/yarn#5042 for more information.
---
https://github.com/mui-org/material-ui/pull/13055
> Add integrity hashes to yarn.lock

- packages/react-jss/package.json
- yarn.lock
Installing external types can have a problem when the end user also installs the same types package.
As we shouldn't force someone to install the @types/react package, I just moved to the dev dependencies. I think we can expect someone to have the appropriate package installed when using `react-jss` and using typescript
__Corresponding issue (if exists):__ #976
> Move react-jss types to dev dependencies

- docs/jss-plugin-extend.md
The demo links are broken for the extend plugin.
> Fix broken demo links

- changelog.md
- packages/jss-starter-kit/.size-snapshot.json
- packages/jss-starter-kit/package.json
- packages/jss-starter-kit/src/index.js
Fix `react-jss` export and add some missing exports from `jss`
__Corresponding issue (if exists):__ #948
> Fix react-jss exports from jss-starter-kit

- .travis.yml
Currently, Travis builds the packages before running the size snapshot matches, which causes them always to pass
> Fix order of travis execution

- changelog.md
- packages/jss-plugin-camel-case/.size-snapshot.json
- packages/jss-plugin-camel-case/src/index.js
- packages/jss-plugin-camel-case/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
Currently, css variables are also being hyphenated.
__Corresponding issue (if exists):__ #1012
> [jss-plugin-camel-case] Support css vars better

- lerna.json
- package.json
This fixes the publishing finally.
For all of the below scripts, the dist tag will be automatically set.
How to publish now (there are five scripts):
`release:patch` -> Release a new patch version
`release:minor` -> Release a new minor version
`release:major` -> Release a new major version
If we are on an alpha version, any of the above scripts will mature the version.
I think we only need to have a new alpha version in case of major versions, that's why only the major version exists here.
`release:alpha:major` -> Release a new alpha version of a new major version This will increment the major version and add a `-alpha.0` suffix
`release:prerelease` -> Release a new prerelease version. This will increment the prerelease number.
> Update publish scripts

- package.json
- packages/jss-plugin-camel-case/.size-snapshot.json
- packages/jss-plugin-camel-case/package.json
- packages/jss-plugin-isolate/.size-snapshot.json
- packages/jss-plugin-isolate/package.json
- packages/jss-plugin-vendor-prefixer/.size-snapshot.json
- packages/jss-plugin-vendor-prefixer/package.json
- packages/jss-plugin-vendor-prefixer/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
- rollup.config.js
- yarn.lock
In this diff I upgraded
- hyphenate-style-name
- css-initials
- css-vendor
which were converted to esm.
This means, that all jss and all plugins may be consumed by unpkg with
module flag like https://unpkg.com/jss-preset-default?module
We probably may get rid from unpkg prop in favour of `?module` flag for
non react packages.
> Upgrade all esm ready packages

- changelog.md
- packages/jss-plugin-rule-value-function/.size-snapshot.json
- packages/jss-plugin-rule-value-function/src/index.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/jss/.size-snapshot.json
- packages/jss/src/RuleList.js
- packages/jss/src/plugins/styleRule.js
- packages/jss/tests/functional/sheet.js
- packages/react-jss/.size-snapshot.json
- packages/react-jss/tests/dynamic-styles.js
> Fix removing styles from function rules 

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/withStyles.js
- packages/react-jss/src/withStyles.test.js
Replaces any whitespaces in a components display name with `-`.
__Corresponding issue:__ #938
> [react-jss] Fix display names with spaces inside

- changelog.md
- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/JssProvider.test.js
- packages/react-jss/src/types.js
- packages/react-jss/src/withStyles.js
- packages/react-jss/tests/dynamic-styles.js
- packages/react-jss/tests/theming.js
This adds the dynamic rules to the static sheet instead of creating a new sheet for every component instance.
I haven't updated the tests, but this should also fix the issues with having to different sheets in `react-jss` (`compose` behaves a little bit different, dynamic keyframe names aren't possible).
__Corresponding issue (if exists):__ #1037
> [react-jss] Add dynamic rules to static sheet

- changelog.md
- packages/jss/.size-snapshot.json
- packages/jss/src/StyleSheet.js
- packages/react-jss/src/JssProvider.test.js
This fixes generating the styles when no `Renderer` is present.
__Corresponding issue (if exists):__ #1062
> [jss] Fix SSR rendering

- changelog.md
- packages/jss-plugin-camel-case/.size-snapshot.json
- packages/jss-plugin-camel-case/src/index.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
startsWith is not supported by IE 11
N/A
> Improve IE 11 support

- packages/jss-plugin-default-unit/src/index.d.ts
It seems that this plugin does not require me to pass the options.
https://github.com/cssinjs/jss/blob/27e2428297fa227d72d45d5757a74169edf70850/packages/jss-plugin-default-unit/src/index.js#L63
But the typespec is forcing me to pass a value.
> Fix typspec for default unit plugin

- changelog.md
- packages/jss/.size-snapshot.json
- packages/jss/src/plugins/keyframesRule.js
- packages/jss/tests/integration/sheet.js
__Corresponding issue (if exists):__ #1098
> Add escaping of keyframe names

- packages/react-jss/src/index.d.ts
Match TypeScript type defs with flow ones, which seems to be the correct one.
`theming` was required in TypeScript defs.
> Match ts types to flow types, theming is optional

- changelog.md
- packages/jss/.size-snapshot.json
- packages/jss/src/DomRenderer.js
- packages/jss/tests/functional/sheet.js
- packages/react-jss/.size-snapshot.json
> Fix adding a value rule after adding an invalid one

- packages/react-jss/src/index.d.ts
Export `useTheme` in TypeScript declaration.
Still missing: Declaration and export of `createUseStyles` fn.
> Export useTheme in TypeScript declaration

- changelog.md
- scripts/update-changelog.js
I think it's worth trying because the changelog is the ultimate place where people look into who care and use the project directly, not as part of some other library.
Hopefully, this won't be perceived as some annoying ad or spam.
> Add support hint to the changelog

- changelog.md
- docs/jss-api.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-vendor-prefixer/.size-snapshot.json
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/jss/.size-snapshot.json
- packages/jss/src/SheetsRegistry.js
- packages/jss/src/plugins/conditionalRule.js
- packages/jss/src/plugins/keyframesRule.js
- packages/jss/tests/integration/sheetsRegistry.js
- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/JssProvider.test.js
- packages/react-jss/test-utils/createBasicTests.js
- registry now returns all sheets from .toString() by default, not only attached, since conditional rendering is not possible on the server
- on the client you can pass now .toString({attached: true}) to get only attached sheets, we assume use cases doing that on the client are rare
> Fix SSR for Hooks based implementation

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/withStyles.js
Fixes #1143.
Per the discussion in #1140 and, prior to that, #1089, sheets should not be attached during server-side rendering.
Now that #1148 has been merged, server rendering is working for the hook API (`createUseStyles()`) but the HOC (`withStyles()`) hasn't been updated yet so still warns (incorrectly) `Rule is not linked. Missing sheet option "link: true"` on the server.
This PR brings the HOC implementation into line with the hook implementation - adding the sheet to the `SheetsRegistry` when the component is constructed, and not attaching (managing) it until the component is mounted (which never occurs on the server).
> HOC should not attach sheets until mount

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/utils/sheets.js
- packages/react-jss/test-utils/createDynamicStylesTests.js
I've found that code like this:
```javascript
injectSheet({
button: {
'&::before': {
content: '""',
height: () => 1
}
}
})(Component)
```
Results in CSS like this:
```css
.Component-button-0-2-31 {}
.Component-button-0-2-31::before {
content: "";
}
.Component-button-0-0-2-32 {}
.Component-button-0-0-2-32::before {}
```
That is, the result of the function value, `height: 1px;`, is missing.
This feature works in `react-jss` v8.6.1 so seems like a regression somewhere between then and v10.
This seems to be specific to `react-jss` because the test in [plugin-nested.test.js#L180](https://github.com/cssinjs/jss/blob/master/packages/jss-plugin-rule-value-function/src/plugin-nested.test.js#L180) does something very similar and passes.
This PR adds failing tests to `react-jss`. I haven't figured …
> Nested function values not working in React

- changelog.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-rule-value-function/.size-snapshot.json
- packages/jss-plugin-rule-value-function/src/function-rules.test.js
- packages/jss-plugin-rule-value-function/src/index.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
https://github.com/cssinjs/jss/issues/1159
> Support falsy value from fn rule

- docs/jss-plugin-nested.md
Just a small fix that resolves the confusion around how referencing local rules works.
> jss-plugin-nested docs fix

- changelog.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-vendor-prefixer/.size-snapshot.json
- packages/jss-plugin-vendor-prefixer/src/index.js
- packages/jss-plugin-vendor-prefixer/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
> Fix fallbacks support in jss-plugin-vendor-prefixer

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/withStyles.js
react-jss withStyles HOC returns component that has non-conventional naming.
Each styled component had the displayName "JssContextSubscriber" that makes hard jest snapshot testing (shallow)
#1211 
@HenriBeck Here is the possible solution I have mentioned before.
> Fix(withStyles): HOC return component with standard displayName

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
`isFirstRender` is broken when using react-hot-loader, as it unmounts and remounts the components, but preserves hook state all the way through, including `isFirstRender`.
The `removeDynamicRules` hook runs first, and an error is thrown once `updateDynamicRules` runs as the rules have been removed.
With those changes everything should run in the proper order.
> refactor createUseStyles to work with react-hot-loader

- changelog.md
- packages/react-jss/src/index.d.ts
#1203
Add type alias for `WithStyles`
> Add type alias for WithStylesProps

- packages/react-jss/src/index.d.ts
Fix
TS-error in this case:
```ts
import React from 'react'
import { createUseStyles } from 'react-jss'
import { createTheming } from 'theming'
const context = React.createContext({})
const theming = createTheming(context)
const styles = {
container: {
backgroundColor: 'green'
}
}
const useWithoutThemeStyles = createUseStyles(styles, { theming })
export { useWithoutThemeStyles }
```
Error:
```
Argument of type '{ theming: Theming<{}>; }' is not assignable to parameter of type 'CreateUseStylesOptions'.
Object literal may only specify known properties, and 'theming' does not exist in type 'CreateUseStylesOptions'.
```
> [react-jss] fixed ts typings for hook, created common interface for options

- packages/jss/.size-snapshot.json
- packages/jss/src/plugins/fontFaceRule.js
- packages/jss/tests/integration/rules.js
> Fix multiple .addRule calls with font-face

- packages/jss/src/index.d.ts
--
The `InsertionPoint` typings only allow `string`s and `HTMLElement`s. The following code currently results in a type error, but works fine:
```ts
import { create } from "jss";
const comment = document.createComment("hi");
// ... add comment to the DOM ...
const jss = create({ insertionPoint: comment });
```
^- Not sure if any of them are needed for this PR.
> Allow a Comment node as insertion point

- docs/jss-plugin-rule-value-function.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-rule-value-function/.size-snapshot.json
- packages/jss-plugin-rule-value-function/src/function-rules.test.js
- packages/jss-plugin-rule-value-function/src/index.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
- webpack.config.js
#1057 
Add warning when user tries to use a function value inside a function rule.
> Add warning when using a function value inside a function rule

- docs/projects.md
I just created these tools, they are very comprehensive and support:
* nested selectors, convert class selectors to $ references
* `@keyframes` and add $ to animation name references
* context property
* fallbacks
* `@global`
* `!important`
* `@font-face`
> docs(projects.md): add links to my new CSS to JS styles converters

- docs/jss-plugin-default-unit.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-default-unit/.size-snapshot.json
- packages/jss-plugin-default-unit/src/index.js
- packages/jss-plugin-default-unit/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
#1291 
Adds the ability to transform values when adding units to them.
> [default-unit] Allow options to pass function transforms in

- packages/react-jss/src/index.d.ts
Let createUseStyles have the default theme type. Like this:
Just add this to your project to work
```typescript
declare module 'react-jss' {
interface DefaultTheme {
...
}
}
```
> typescript support for createUseStyles theme

- changelog.md
- docs/jss-api.md
- packages/jss/.size-snapshot.json
- packages/jss/src/index.d.ts
- packages/jss/src/index.js
- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/JssProvider.test.js
- packages/react-jss/src/createUseStyles.test.js
- packages/react-jss/src/index.d.ts
- packages/react-jss/src/index.test.js
- packages/react-jss/src/utils/geDynamicStyles.test.js
- packages/react-jss/src/utils/getDynamicStyles.js
- packages/react-jss/src/utils/mergeClasses.test.js
- packages/react-jss/src/utils/sheets.js
- packages/react-jss/src/utils/sheetsMeta.js
- packages/react-jss/tests/dynamicStyles.js
> Move getDynamicStyles into react-jss package

- packages/react-jss/src/index.d.ts
#1308
#1309
This PR changes the type definition of `createUseStyles<Theme>(styles, options?: CreateUseStyles)` so it passes the `Theme` type parameters to the options type: `createUseStyles<Theme>(styles, options?: CreateUseStyles<Theme>)`.
It also re-exports the `Theming` type, so users of `createTheming` can do explicit typing of the result: `const theming : Theming = createTheming(...` without having to add the `theming` package to the direct dependencies.
> TypeScript fixes for #1308 and #1309

- packages/jss-plugin-rule-value-function/package.json
> add tiny-warning to deps

- changelog.md
- packages/react-jss/src/index.d.ts
- packages/react-jss/src/index.test.tsx
- tsconfig.json
Hello, dear colleagues!
I fixed an issue connected with react default props in typescript.
You can read more about processing of react default props in typescript here: 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx
In short, they calculate resulted props with help of `JSX. LibraryManagedAttributes` small function.
So, as you can see, in PR I used this helper to calculate component props types according official documentation.
Thanks for your attention!
> fix(react-jss/types): fix react default props types support

- packages/react-jss/src/index.d.ts
The problem is that my app `Theme` interface didn't match to `unknown` theme type.
So I think `any` type would be better in this case.
> fix(react-jss): fix react-jss theme types

- packages/react-jss/src/index.d.ts
- packages/react-jss/src/index.test.tsx
Can't pass innerRef prop
Add support for innerRef in types
> [react-jss] TypeScript: Added support for innerRef prop

- changelog.md
- docs/jss-plugin-extend.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-extend/.size-snapshot.json
- packages/jss-plugin-extend/src/index.js
- packages/jss-plugin-extend/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
#1345
Now plugin can extend both named and object in the array.
> fix(extend): extends multiple named styles (fix #1345)

- packages/jss/src/utils/createGenerateId.js
Brings this into alignment with the Typescript annotation for this same function:
```
export type CreateGenerateId = (options?: CreateGenerateIdOptions) => GenerateId
```
I didn't open an issue, but can if that would be helpful for tracking
The TS and Flow types for GreateGenerateId disagree on the optionality of the options parameter. It *appears* to me that options is meant to be optional and thus the TS annotation is more correct. I've made the corresponding update to the flow type.
> Fix Flow typing for CreateGenerateId

- rollup.config.js
Running `yarn build` on windows machines causes errors due to the way external modules are calculated. This is the error message:
```
(plugin size-snapshot) Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Jss.js' in '/'
```
I found another library that had the exact same problem. This PR mirrors the fix that they created.
https://github.com/doczjs/docz/issues/783
> fix: Made it possible for windows to run yarn build

- changelog.md
- packages/jss/package.json
- yarn.lock
None
Bump csstype to avoid possible type conflicts. All `@types/*` packages have already switched: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46435
- ~[ ] Add tests if possible~
- ~[ ] Add documentation~
> feat: Bump csstype to 3.0.2

- .flowconfig
- changelog.md
- package.json
- packages/css-jss/.size-snapshot.json
- packages/css-jss/src/createCss.js
- packages/css-jss/src/createCss.test.js
- packages/jss-plugin-extend/.size-snapshot.json
- packages/jss-plugin-extend/src/index.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/jss/.size-snapshot.json
- packages/jss/src/Jss.js
- packages/jss/src/RuleList.js
- packages/jss/src/SheetsRegistry.js
- packages/jss/src/types/jss.js
- packages/jss/src/utils/toCss.js
- packages/react-jss/.size-snapshot.json
- packages/react-jss/package.json
- packages/react-jss/src/JssProvider.js
- packages/react-jss/src/createUseStyles.js
- packages/react-jss/src/jsx.js
- packages/react-jss/src/styled-props-filter.test.js
- packages/react-jss/src/styled.js
- packages/react-jss/src/styled.test.js
- packages/react-jss/src/types.js
- packages/react-jss/src/utils/sheetsMeta.js
- packages/react-jss/src/withStyles.js
- packages/react-jss/tests/styledSystem.js
- yarn.lock
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/theming/src/create-with-theme.js:23:18
Cannot spread props because Flow cannot determine a type for props [1]. object type [2] is
inexact, so it may contain ref with a type that conflicts with ref's definition in props [1].
Try making object type [2] exact. [cannot-spread-inexact]
node_modules/theming/src/create-with-theme.js
20│             '[theming] Please use withTheme only with the ThemeProvider'
21│           );
22│
[1]  23│           return <Component theme={theme} ref={ref} {...props} />;
24│         }}
25│       </context.Consumer>
26│     ));
/private/tmp/flow/flowlib_36a9420e/react.js
[2] 159│ declare type React$ComponentType<-Config> = React$AbstractComponent<Config, mixed>;
```
> Upgrade flow-bin to 0.131.0 and migrate types

- docs/csp.md
The doc is using old style-loader API.
Based on the new API, `attrs` has been changed to `attributes` https://webpack.js.org/loaders/style-loader/#attributes
> docs(csp): update style-loader config

- docs/react-jss.md
Adding a section explaining the name prop in the options object to add classname prefix on Module/Component level
> Update Classname Example

- changelog.md
- packages/jss/package.json
- packages/jss/src/index.d.ts
- packages/jss/tests/jss-tests.ts
- packages/jss/tests/types/Styles.ts
- yarn.lock
```typescript
const jss = createJSS(createDefaultJSSPreset());
jss.createStyleSheet(
{
myClassName: someObservable$,
},
{
link: true,
},
).attach();
```
should work in TypeScript, and [used to work with `@types/jss`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/de655960b603d6b47f7030674f084780c76e045f/types/jss/css.d.ts).  JSS now supplies its own types, which don't include `Observable` support.  This PR adds them back.
As @worudso alluded to in #1035, a better solution would only include the `Observable` type if users had installed the Observable plugin.  Otherwise, users could be frustrated if the typecheck passes for `createStyleSheet(someObservables)` but it fails at runtime.
However, that solution would require bigger and more thoughtful changes to the typings.  This PR is …
> Restore TypeScript support for Observable styles

- packages/css-jss/package.json
- packages/jss-plugin-cache/package.json
- packages/jss-plugin-camel-case/package.json
- packages/jss-plugin-compose/package.json
- packages/jss-plugin-default-unit/package.json
- packages/jss-plugin-expand/package.json
- packages/jss-plugin-extend/package.json
- packages/jss-plugin-global/package.json
- packages/jss-plugin-isolate/package.json
- packages/jss-plugin-nested/package.json
- packages/jss-plugin-props-sort/package.json
- packages/jss-plugin-rule-value-function/package.json
- packages/jss-plugin-rule-value-observable/package.json
- packages/jss-plugin-template/package.json
- packages/jss-plugin-vendor-prefixer/package.json
- packages/jss-preset-default/package.json
- packages/jss-starter-kit/package.json
- packages/jss/package.json
- packages/react-jss/package.json
https://github.com/cssinjs/jss/issues/979
Prevent the test files from being published to NPM.
I'm not super comfortable with how lerna works, but I believe this is what's needed.
> perf: remove test files from the package

- changelog.md
- docs/react-jss.md
- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-default-unit/.size-snapshot.json
- packages/jss-plugin-default-unit/src/defaultUnits.js
- packages/jss-plugin-default-unit/src/index.js
- packages/jss-plugin-default-unit/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
Fixes https://github.com/cssinjs/jss/issues/1363.
Currently, no default units are applied to a zero value. While the CSS spec allows this for length units like `px` (see https://www.w3.org/TR/css-values-3/#lengths), this causes incorrect CSS to be generated for other units like `ms`, which the browser then ignores.
An example of this bug is provided in the linked issue (https://github.com/cssinjs/jss/issues/1363):
This PR makes two changes to the logic in `packages/jss-plugin-default-unit/src/index.js`:
* It prevents a value of `0` from being returned early in the initial falsy value check.
* It adds a default unit (if available) to all numeric values, except for the special case of `0px`.
While generating `0px` instead of `0` would also be acceptable when the default unit is `px`, it may …
> [default-unit] Fix missing default unit for 0ms and 0%

- packages/jss-plugin-default-unit/src/defaultUnits.js
resolve #1348
Add gap to defaultUnits
> feat(units): add `gap`

- packages/jss/src/index.d.ts
typescript can't work with   [K in keyof NormalCssProperties | string]
type definition
> fix: jssStyle type

- scripts/build.js
- scripts/match-snapshot.js
Just ran into issue while trying to run `yarn build` and `yarn check:snapshots`, because `shell.exec` calls didn't expect project directory to contain spaces.
> Allow project to be in a directory that contains spaces

- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-default-unit/.size-snapshot.json
- packages/jss-plugin-default-unit/src/defaultUnits.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
https://github.com/cssinjs/jss/issues/1435
Adds default unit as `px` for `row-gap` css property
> feat: add px as default unit for row-gap property

- packages/jss-plugin-default-unit/src/defaultUnits.js
https://github.com/cssinjs/jss/issues/1437
> feat: add px as default unit for text-decoration-thickness property

- packages/css-jss/.size-snapshot.json
- packages/jss-plugin-default-unit/.size-snapshot.json
- packages/jss-plugin-default-unit/src/index.js
- packages/jss-plugin-default-unit/src/index.test.js
- packages/jss-preset-default/.size-snapshot.json
- packages/jss-starter-kit/.size-snapshot.json
- packages/react-jss/.size-snapshot.json
Fixes #1445. The new test case fails without the fix (locally, not in the cloud as it's using an old version of Chrome).
I think that this bug will require a release sooner rather than later @kof.
> Fix crash Chrome 88

- packages/jss/.size-snapshot.json
- packages/jss/src/utils/globalThis.js
N/A, but can create if that would be helpful. 
Now that [`globalThis` is generally available on all the latest platforms](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility), `globalThis.js` can be improved by first checking for the presence of `globalThis`. 
My motivation: At Agoric, we have a secure version of JavaScript called SES. Under SES, `globalThis` exists, but `window`, `self`, and `Function('return this')()` are all undefined for security reasons. So, `jss` was failing for us, but by including `globalThis`, it will safely succeed even under our security requirements. 
I would be happy to add a test, but I wasn't sure what to test and where to put it. It looks like there are no unit tests for `globalThis`. I'm …
> chore: edit globalThis.js to first check for `globalThis`

- contributing.md
- packages/react-jss/src/index.d.ts
- packages/react-jss/src/index.test.tsx
This PR fixes a number of things that make react-jss's `createUseStyles` less convenient for TypeScript users.
1. Defining `createUseStyles` is tedious because you need to pass the theme as a type argument every time, which has to be imported from somewhere (`createUseStyles<MyTheme>(theme => { ... })`)
2. If you supply a type argument, then you lose one of the most important type safety features - the typecheck of the class names:
This is because, if you supply a type argument, the union type (`"myHeader" | "myFooter"` in the screenshot) just becomes `string`.
&shy;
To fix this, you have to duplicate every class name, and now the code looks horrendous:
```js
createUseStyles<MyTheme, "myHeader" | "myFooter">(theme => ({ 
myHeader: { margin: 0 },
myFooter: { padding: 0 },
}))
```
3. For …
> support global typescript theme definition

- packages/react-jss/src/index.d.ts
The `classes` prop created by the `withStyles` function is meant to be an optional parameter where you can provide some or all of the style classes.
Imagine a somewhat contrived snippet like:
```typescript
import React from "react";
import withStyles, { WithStylesProps } from "react-jss";
import clsx from "clsx";
const styles = {
root: { display: "block" },
blue: { color: "blue" },
};
type Props = { blue?: boolean } & WithStylesProps<typeof styles>;
const Component = ({ blue = false, classes }: Props) => (
<div className={clsx(classes.root, { [classes.blue]: blue })}>
Hello, world!
</div>
);
const StyledComponent = withStyles(styles)(Component);
```
You'd expect to be able to use it in any of the following ways:
```tsx
<StyledComponent />
<StyledComponent blue />
<StyledComponent …
```
> fix: allow partial `classes` prop in withStyles

- packages/jss/src/index.d.ts
Closes #1439, Closes #1452, Closes #806, possibly fixes #776
Make auto-complete work for Typescript and/or VSCode users like in this screenshot:
This is **not** a breaking change. In the example above, folks can still type `display: "dhgjdkfhg"` and TS will accept it. This PR only makes auto-complete work. It deliberately doesn't add type-safety because that needs to wait for a semver-major release.
> make auto-complete of createUseStyles value work

- packages/jss/src/index.d.ts
Typescript not working I changed import from `csstype` and now that working
> fix: type import from csstype

- .eslintignore
- packages/jss/src/index.d.ts
- packages/jss/tests/types/Styles.ts
- packages/react-jss/src/index.d.ts
- packages/react-jss/tests/types/createUseStyles.ts
- packages/react-jss/tests/types/withStyles.tsx
This PR aims to ensure that the `createUseStyles` hook has accurate TS intellisense for `props` and `theme`s. The details of the work can be found in the commit message. Note that as a result of cascading effects, this PR also improves the types for the deprecated `withStyles` HOC. This should satisfy #1273 and #1431.
These are TypeScript changes **only**, as only these changes will be visible to the TypeScript users. These are the minimal changes necessary to improve the user experience for TS devs. Flow is separate and unrelated to the user, and I'm not so familiar with it, so it's simplest to add flow changes in a separate commit (if that's acceptable). (If someone else familiar with Flow could apply the changes, that would be helpful. I've already supplied the TS types, so it should …
> Improve Types for Hooks

- changelog.md
This is a PR to specify the changes from #1460 in the changelog. These details are related to #1460 _only_. With guidance, if desired, I would gladly add any additional details that seem relevant to v10.6.0.
> Update Changelog (v10.6.0)

- docs/react-jss-ts.md
- docs/react-jss.md
- packages/react-jss/tests/types/docs.tsx
This is a PR to add documentation for using hooks with TypeScript. I didn't expect 10.6.0 to get released this fast. But since it's out there, I think getting these docs out as soon as possible is optimal. It will help people who've been waiting for better TS support, and it will also give better ideas on how to migrate older code.
Tests are added under a `docs.tsx` file. If the examples are simple, then any TS code that gets added to the documentation should probably have something like this. Implicit types are complicated, so it's important to know they work as expected before suggesting the change to other users.
> Add Documentation for Using Hooks with TypeScript

- .github/PULL_REQUEST_TEMPLATE.md
This is a simple PR to provide slight enhancements to the PR template. Commenting out text that doesn't belong in the submitted PR helps clarify what the contributor is (or isn't) expected to provide. Additionally, it reduces visual overloading for reviewers when the contributor forgets to remove/replace the template text.
> Add Slight Improvements to PR Template

- packages/jss/src/DomRenderer.js
We have `GetPropertyValue` but `getPropertyValue` not used it
> add forgotten type for getPropertyValue

- packages/jss/.size-snapshot.json
- packages/jss/src/utils/createGenerateId.js
I used `GenerateId` type inside of `createGenerateId`
> remove repetition type definition in createGenerateId

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/withStyles.js
> Migrate withStyles to use hooks

- packages/jss/package.json
- packages/jss/src/index.d.ts
- packages/jss/tests/jss-tests.ts
- packages/jss/tests/types/Styles.ts
None.
I came here looking to see how this project was using observables, and I figured out it was only using one of the dependencies for the observable type itself. I've simplified that and reduced the dependencies, since there was not really a run-time dependency at all, only build time.
This was a refactor to reduce the number of dependencies and simplify things a bit. Just making sure you have defined the interface you expect for observables. There was no attempt to change functionality at all.
Eliminated the dependency on an external run-time project for the basic observable contract that was only used for TypeScript.
(attn @appsforartists)
> Add minimal type to reduce dependency graph

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
- packages/react-jss/src/createUseStyles.test.js
Here https://github.com/cssinjs/jss/pull/1460/files was added type for `data` in `useStyles`. But the attempt to pass the `theme` prop to components was unsuccessful (in fact, it didn't affect anything).
So, in this pull request I have aligned the code and TS types and added the necessary logic to the `createUseStyles`.
* [react-jss] add using `theme` prop if passed inside `useStyles`
> [react-jss] add using theme prop if passed inside useStyles

- docs/jss-syntax.md
Document more uses for `&` when dealing with high specificity selectors
Added more documentation for use cases when using `&`.
> enhancement: jss-syntax-documentation-for-high-specificity

- docs/users.md
Added [morfeo](https://morfeo.dev/) to `Who is using JSS list`.
I would like to add [morfeo](https://morfeo.dev/) to the list of `Who is using JSS list`. I'm the author of this library and JSS is a fundamental piece of morfeo, without JSS it could not have been possible to create morfeo.
Added [morfeo](https://morfeo.dev/) to `Who is using JSS list`.
> feat: added morfeo

- packages/jss/.size-snapshot.json
- packages/jss/src/RuleList.js
- packages/jss/src/SheetsRegistry.js
- packages/jss/src/index.d.ts
- packages/jss/src/plugins/conditionalRule.js
- packages/jss/src/plugins/fontFaceRule.js
- packages/jss/src/plugins/keyframesRule.js
- packages/jss/src/types/jss.js
- packages/jss/src/utils/getWhitespaceSymbols.js
- packages/jss/src/utils/toCss.js
- packages/jss/tests/integration/rules.js
- packages/jss/tests/integration/sheetsRegistry.js
This PR adds a new option `format` to `SheetsRegistry.toString` so whitespaces are removed from stringified CSS.
```es6
jss.createRule('a', {float: 'left', width: '1px'})
// Default
rule.toString()
// outputs:
// .a-id {
//   float: left;
//   width: 1px;
// }
// With format:false
rule.toString({format: false}))
// outputs:
// .a-id{float:left;width:1px;}
```
Indentation and line breaks are removed when `format: false` is passed to `SheetsRegistry.toString` or `rule.toString` methods.
- Add a new option `format` for removing whitespaces in `SheetsRegistry.toString(options)`
> feat(jss): Add format option to SheetsRegistry.toString()

- packages/jss/src/SheetsRegistry.js.flow
I'd like to add a missing property on which my IDE complains.
Index property itself is used at least here https://github.com/cssinjs/jss/blob/02cb79b345570f2495ce9650641593c8cec8b47f/packages/jss/src/Jss.js#L73.
No warnings from IDE when the `index` property of sheets is used.
Just a single extra property.
> fix: add missing index property

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
- packages/react-jss/src/createUseStyles.test.js
- packages/react-jss/src/utils/getSheetClasses.js
`getSheetClasses` always return new object even `sheet` and `dynamicRules` haven't any change
Also I wrote a small test to keep it in future
So, I memoized it to prevent this behavior
Improve performance at `useStyle`
> Keep classes ref when sheet and dynamicRules have not any change

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
Fixes failing tests in #1604 by managing the sheet immediately after create, instead of doing so in a separate effect.
> fix(useStyles): manage sheet on create and then add dynamic styles

- packages/css-jss/package.json
- packages/jss-plugin-cache/package.json
- packages/jss-plugin-camel-case/package.json
- packages/jss-plugin-compose/package.json
- packages/jss-plugin-default-unit/package.json
- packages/jss-plugin-expand/package.json
- packages/jss-plugin-extend/package.json
- packages/jss-plugin-global/package.json
- packages/jss-plugin-isolate/package.json
- packages/jss-plugin-nested/package.json
- packages/jss-plugin-props-sort/package.json
- packages/jss-plugin-rule-value-function/package.json
- packages/jss-plugin-rule-value-observable/package.json
- packages/jss-plugin-template/package.json
- packages/jss-plugin-vendor-prefixer/package.json
- packages/jss-preset-default/package.json
- packages/jss-starter-kit/package.json
- packages/jss/package.json
- packages/react-jss/package.json
> If the package.json for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives:
> ```json
> "repository": {
>   "type" : "git",
>   "url" : "https://github.com/facebook/react.git",
>   "directory": "packages/react-dom"
> }
> ```
> — https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository
I use a lot https://njt.vercel.app/ to jump to different packages information,
and with this PR we can know exactly what package in what folder lives
Made the changes with a script to make it easier 🙂
https://gist.github.com/iamandrewluca/5cc85b56a595056f0099d04ed6dd8a79
> chore: add repository directory for all packages.json

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/JssContext.js
- packages/react-jss/src/JssProvider.js
- packages/react-jss/src/createUseStyles.js
- packages/react-jss/src/createUseStyles.test.js
- packages/react-jss/src/flow-types.js
- packages/react-jss/src/index.d.ts
- packages/react-jss/test-utils/createCommonBaseTests.js
Using `renderToString` in a browser environment is completely legal; however, in such cases, the `isInBrowser` check will be truthy - causing some parts to misbehave (like choosing the wrong effect, useLayoutEffect over useEffect).
This PR allows the user to supply a custom `isSSR` prop to the `JssProvider` overriding the default `isInBrowser` check.
Also necessary for fixing failing tests in #1609.
> feat(JssProvider): provide custom isSSR flag

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
#1608 fixed the failing tests caused by #1604, but doing so reintroduced the original bug breaking React 18 support...
`manageSheet` **must** be in a separate `useEffect` because it can run more times than `useMemo` - like during fast-refresh or running in strict mode. Since `manageSheet` is currently in the `useMemo`, `unmanageSheet` from `useEffect` gets **called more times** than `manageSheet`, unmanaging the sheet while in use.
All `renderToString` tests broke with #1604 because `useEffect`s don't run during SSR. The fix is included [here](https://github.com/cssinjs/jss/pull/1609/commits/21f87aeafee581c08d11b4797e238924b8a04672); however, your tests are wrongly set up since `isInBrowser` will return `true` when using `renderToString`.
@kof I don't want to tingle with your tests setup, …
> fix(useStyles): manageSheet must be in the same effect as unmanageSheet

- packages/jss/.size-snapshot.json
- packages/jss/src/DomRenderer.js
- packages/jss/src/index.d.ts
- packages/jss/src/utils/toCssValue.js
- packages/jss/tests/functional/sheet.js
Update stylesheet if `!important` flag is set before and after the update
- All tests passed
- It wasn't a public API
- A issue is about when you want to update a CSS rule value with a `!important` flag
> 1207 - update stylesheet if !important is set

- packages/react-jss/.size-snapshot.json
- packages/react-jss/src/createUseStyles.js
https://github.com/cssinjs/jss/issues/1618
By this PR JSS consumers can use React 17 and 16
Fix `useInsertionEffect` import issue on react 16 and 17
> fix import issue about useInsertionEffect on react 17
