cssinjs/jss

bin/cssToJss.js, dist/jss.js, examples/angular/app.js, examples/calendar/components/calendar/index.js, examples/calendar/components/canvas/index.js, examples/calendar/components/event/content-tpl.js, examples/calendar/components/event/index.js, examples/calendar/components/events-manager/distribute.js, examples/calendar/components/events-manager/index.js, examples/calendar/components/timeline/index.js, examples/calendar/components/timeline/marker-tpl.js, examples/calendar/components/utils/index.js, examples/calendar/dist/index.js, examples/calendar/index.html, examples/famous/app.js, examples/topcoat/build.js, lib/Rule.js, lib/StyleSheet.js, lib/plugins.js, test/Rule.js, test/StyleSheet.js
For some reason there are heaps of NO-BREAK SPACE characters in the source code
http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%C2%A0&mode=char
=> Replace NO-BREAK SPACE character with normal space in source code

bower.json, lib/uid.js, package.json
Remove invalid 0x2C character from lib/uid and create patch release
=> Remove invalid character: fix #76

src/rules/FontFaceRule.js, src/rules/Rule.js, src/utils.js, test/Rule.js
Also adds a test case to handle @font-face with multiple styles in an
array
Fixes #199
(corresponding fix to jss-camel-case coming shortly)
=> Add support for array of styles for @font-face rule

tests/functional/sheet.js
https://github.com/jsstyles/jss/issues/252
=> should register the rule after sheet.detach()

src/PluginsRegistry.js, src/RulesContainer.js, src/StyleSheet.js, src/rules/ConditionalRule.js, src/rules/Rule.js, tests/integration/rules.js, tests/integration/sheet.js
I mixed those 2 things, because I wanted to how running plugins in the main repository will work out to fix a bug in a plugin repository.
The problem was that to fix a bug in jss-nested I needed to fix JSS first and then to fix jss-nested. I wanted to be able to do that from one test suite and this was possible.
=> Run plugins tests + fix a bug #285

package.json
Closes #303 
@kof it says "in all repositories". Can you add a to-do list of where it makes sense to integrate here?
=> Added lint-staged with autofix config for *.js

.babelrc
@kof 
Fixes the issue with `stage-0` and up not working properly.
=> Fix babel preset ordering

contributing.md, docs/setup.md, package.json, readme.md
As discussed in https://github.com/cssinjs/jss/issues/338
=> Require Node 4+ (fix #338)

src/index.js
this is for my PR to `react-jss` to create a `JssSheetsRegistry` component that passes a `SheetsRegistry` down through context.
=> export SheetsRegistry

docs/plugins.md
Solves https://github.com/cssinjs/jss/issues/374
And is connected with jss-preset-default PR fix https://github.com/cssinjs/jss-preset-default/pull/4
=> #374 Fix jss-compose conflict with jss-expand

.babelrc, package.json
=> Implement `babel-runtime`

changelog.md, package.json, src/PluginsRegistry.js, src/RulesContainer.js, src/StyleSheet.js, src/backends/DomRenderer.js, src/index.js, src/plugins/ConditionalRule.js, src/types.js, src/utils/createRule.js, tests/functional/sheet.js, tests/integration/jss.js, tests/utils.js
Changes needed to fix https://github.com/cssinjs/jss/issues/380 and https://github.com/cssinjs/jss/issues/387
This PR is required for the actual fix https://github.com/cssinjs/jss-global/pull/5
=> Bug nested globals

readme.md
=> Added Aesthetic to libraries list

docs/users.md
=> Fix react-styleguidist name and URL

docs/external-projects.md
Dear,
Thank you for great project.
We would like to share our project and to make SCSS-to-JSS migration more comfortable.
=> Add PreJSS to Convenience in external-projects

docs/users.md
Dear,
Thank you for the great project again and again.
I would like to add our service company. We use JSS a long time.
=> Add Axept company to users list

docs/plugins.md, src/PluginsRegistry.js, src/StyleSheet.js, src/plugins/RegularRule.js, src/types.js, tests/integration/hooks.js
=> Implement onChangeValue hook

src/Jss.js, src/types.js
=> Fixed some Flow annotations

flow-typed/cssom.js, package.json, src/RulesContainer.js, src/StyleSheet.js, src/backends/DomRenderer.js, src/types.js, src/utils/linkRule.js, tests/.babelrc, tests/functional/sheet.js, tests/utils.js
Fix https://github.com/cssinjs/jss/issues/511
=> Fix dynamic values for conditional and keyframe rules

changelog.md, docs/js-api.md, src/SheetsManager.js, tests/unit/SheetsManager.js
related https://github.com/cssinjs/react-jss/pull/123#discussion_r128999567
=> add SheetsManager.size

benchmark/tests/linked-sheet.js, package-lock.json, package.json, src/RuleList.js, src/renderers/DomRenderer.js, src/renderers/VirtualRenderer.js, src/types.js, tests/functional/sheet.js
=> Selector escaping 

docs/js-api.md
I may miss something but that’s the only way it works for me.
=> Fix createGenerateClassName docs

.eslintrc, changelog.md, docs/setup.md, karma.conf.js, package-lock.json, package.json, src/utils/createGenerateClassName.js, tests/functional/sheet.js, tests/unit/createGenerateClassName.js, tests/utils.js
=> Add class name escaping for the dev mode

src/utils/escape.js, tests/unit/escape.js
we don't want to force people to install the polyfil, because it is a
rare one right now and it causes setup overhead
=> Use a fallback regex instead of warning

docs/js-api.md
It was not clear to me what exactly should be in the update function param and how does it binds to the style rules. I think this example should help.
=> Function values docs example

benchmark/tests/to-css-value.js, changelog.md, docs/json-api.md, karma.conf.js, package.json, src/renderers/DomRenderer.js, src/rules/StyleRule.js, src/types.js, src/utils/toCssValue.js, tests/functional/function-values.js, tests/integration/rules.js
Original PR https://github.com/cssinjs/jss/pull/631
=> Support array functions from function values + !important

docs/projects.md
Add a project to create Sci-Fi UIs using React and JSS.
=> Add project "Arwes" to docs

src/StyleSheet.js
Fixed StyleSheet.update param types to be the same as RuleList.update
=> Fix flow type definition of StyleSheet.update function

docs/json-api.md
=> Issue #702

.size-snapshot.json, rollup.config.js
Fixes https://github.com/cssinjs/jss/issues/728
=> Replace __VERSION__ in umd bundles

.babelrc, .travis.yml, package-lock.json, package.json, packages/jss/.size-snapshot.json, packages/jss/src/Jss.js, rollup.config.js, scripts/build-lib.js, scripts/build-umd.js, scripts/create-flow-file.js, scripts/get-package-json.js, scripts/prepare.js, webpack.config.js
Because we have problems with the `jss-global` and `jss-preset-default` package, I extracted the changes to the build system out so we can work on other packages before solving those problems.
- Fixed rollup build for other packages
- Fixed inline the correct version
- Fixed Travis tests
=> Updated build script

karma.conf.js, packages/jss-plugin-isolate/.size-snapshot.json, packages/jss-plugin-isolate/LICENSE, packages/jss-plugin-isolate/changelog.md, packages/jss-plugin-isolate/package-lock.json, packages/jss-plugin-isolate/package.json, packages/jss-plugin-isolate/readme.md, packages/jss-plugin-isolate/src/index.js, packages/jss-plugin-isolate/src/index.test.js, packages/jss/tests/index.js
=> Added jss-isolate and renamed it to jss-plugin-isolate

karma.conf.js, packages/jss-plugin-syntax-template/.size-snapshot.json, packages/jss-plugin-syntax-template/LICENSE, packages/jss-plugin-syntax-template/benchmark/tests/createSheet.js, packages/jss-plugin-syntax-template/benchmark/tests/parse.js, packages/jss-plugin-syntax-template/changelog.md, packages/jss-plugin-syntax-template/package-lock.json, packages/jss-plugin-syntax-template/package.json, packages/jss-plugin-syntax-template/readme.md, packages/jss-plugin-syntax-template/src/index.js, packages/jss-plugin-syntax-template/src/index.test.js, packages/jss-plugin-syntax-template/src/parse.js
Forgot the jss-template plugin. Renamed it to jss-plugin-syntax-template.
=> Added jss-template

packages/jss-plugin-syntax-global/src/index.js, packages/jss/src/index.js, packages/jss/src/rules/ConditionalRule.js, packages/jss/src/rules/KeyframesRule.js, packages/jss/src/rules/StyleRule.js, packages/jss/src/types/jss.js
- Update return type of onCreateRule hook for plugins to only return a BaseRule interface
- Added a ParentRule interface which specifies rules to be a RuleList
- Made the parent prop in RuleOptions and RuleListOptions to be of type ParentRule
- Updated interfaces of ConditionalRule and KeyframesRule to be ParentRule
=> Add typings to global plugin

package-lock.json, packages/jss-plugin-cache/.size-snapshot.json, packages/jss-plugin-isolate/.size-snapshot.json, packages/jss-plugin-syntax-compose/.size-snapshot.json, packages/jss-plugin-syntax-default-unit/.size-snapshot.json, packages/jss-plugin-syntax-expand/.size-snapshot.json, packages/jss-plugin-syntax-extend/.size-snapshot.json, packages/jss-plugin-syntax-global/.size-snapshot.json, packages/jss-plugin-syntax-nested/.size-snapshot.json, packages/jss-plugin-syntax-rule-value-function/.size-snapshot.json, packages/jss-plugin-syntax-template/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-preset-default/.size-snapshot.json, packages/jss/.size-snapshot.json, packages/react-jss/.size-snapshot.json, packages/react-jss/package-lock.json, rollup.config.js
Loose mode produces smaller code and reuses less helpers
=> Enable babel loose mode

packages/jss-plugin-syntax-default-unit/src/defaultUnits.js
=> Fixed missing text-shadow property in default units

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
Created a PR template and issue templates for bugs and features.
=> Add github issue and PR templates

packages/jss-plugin-syntax-default-unit/.size-snapshot.json, packages/jss-preset-default/.size-snapshot.json, packages/react-jss/.size-snapshot.json, packages/react-jss/src/createHoc.js, packages/react-jss/src/injectSheet.js, packages/react-jss/src/types.js
Made some small naming improvements of the react-jss types
=> Fix react-jss types

docs/js-api.md
=> Run prettier

packages/react-jss/package.json
__What would you like to add/fix?__ Fix peer dep
__Corresponding issue (if exists):__ As found in #868
=> [react-jss] Fix peer dep of react

packages/jss-plugin-cache/readme.md, packages/jss-plugin-cache/src/index.js
__What would you like to add/fix?__ Use WeakMap for the cache plugin.
__Corresponding issue (if exists):__ #880
=> [jss-plugin-cache] Use WeakMap for cache plugin

docs/users.md
Add one project to the showcase.
=> [docs] Add Onepixel

packages/jss/src/index.d.ts
Declare ES classes as TypeScript classes.
Fixes #970
=> Declare ES classes as TypeScript classes

.gitignore, packages/jss-plugin-cache/package.json, packages/jss-plugin-camel-case/package.json, packages/jss-plugin-compose/package.json, packages/jss-plugin-default-unit/package.json, packages/jss-plugin-expand/package.json, packages/jss-plugin-extend/package.json, packages/jss-plugin-global/package.json, packages/jss-plugin-isolate/package.json, packages/jss-plugin-nested/package.json, packages/jss-plugin-props-sort/package.json, packages/jss-plugin-rule-value-function/package.json, packages/jss-plugin-rule-value-observable/package.json, packages/jss-plugin-template/package.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/package.json, packages/jss-starter-kit/package.json, packages/jss/package.json, packages/react-jss/package.json
Fixes the URL of the `repository` field in the `package.json` files.
__Corresponding issue (if exists):__ #932
=> [all] Fix repo urls

packages/jss-plugin-cache/package.json, packages/jss-plugin-camel-case/package.json, packages/jss-plugin-compose/package.json, packages/jss-plugin-default-unit/package.json, packages/jss-plugin-expand/package.json, packages/jss-plugin-extend/package.json, packages/jss-plugin-global/package.json, packages/jss-plugin-isolate/package.json, packages/jss-plugin-nested/package.json, packages/jss-plugin-props-sort/package.json, packages/jss-plugin-rule-value-function/package.json, packages/jss-plugin-rule-value-observable/package.json, packages/jss-plugin-template/package.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/package.json
Upgrades all of the peer dependencies to 10.0.0-alpha.8 and fixes the range of some of the peer dependencies
=> [all] Fix peer deps

packages/react-jss/package.json, yarn.lock
=> Upgrade theming to v3.0.3

packages/jss-plugin-cache/readme.md, packages/jss-plugin-camel-case/readme.md, packages/jss-plugin-compose/readme.md, packages/jss-plugin-default-unit/readme.md, packages/jss-plugin-expand/readme.md, packages/jss-plugin-extend/readme.md, packages/jss-plugin-global/readme.md, packages/jss-plugin-isolate/readme.md, packages/jss-plugin-nested/readme.md, packages/jss-plugin-props-sort/readme.md, packages/jss-plugin-rule-value-function/readme.md, packages/jss-plugin-rule-value-observable/readme.md, packages/jss-plugin-template/readme.md, packages/jss-plugin-vendor-prefixer/readme.md, packages/jss-preset-default/readme.md, packages/jss-starter-kit/readme.md, packages/jss/readme.md, packages/react-jss/readme.md, readme.md, scripts/create-readme.js
Add some badges to the readme and a link to the docs in the root readme.
=> [docs] Add badges to readmes

changelog.md, docs/setup.md, packages/jss/.size-snapshot.json, packages/jss/src/SheetsManager.js, packages/jss/src/index.d.ts, packages/jss/tests/unit/SheetsManager.js
Update the `SheetsManager` to use a WeakMap.
=> [jss] Update SheetsManager

packages/react-jss/src/index.d.ts
This adds the JssContext to the typescript definitions.
=> [react-jss] Fix TS type definitions

changelog.md, packages/jss-plugin-global/.size-snapshot.json, packages/jss-plugin-global/src/index.js, packages/jss-plugin-global/src/index.test.js, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/jss/.size-snapshot.json, packages/jss/src/renderers/DomRenderer.js, packages/jss/src/types/jss.js, packages/react-jss/.size-snapshot.json
=> Fix dynamic values inside of @global #664

readme.md
The links to the npm website were wrong (they had packages instead of package)
=> Correct npm Links

packages/jss/.size-snapshot.json, packages/jss/src/plugins/keyframesRule.js, packages/jss/tests/integration/sheet.js
__Corresponding issue (if exists):__ #1060
=> [jss] Add support for multiple referenced keyframes

packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json, yarn.lock
Update of css-vendor to 2.0.1
https://github.com/cssinjs/jss/issues/1059
=> Update to css-vendor@2.0.1

changelog.md, packages/jss-plugin-expand/src/props.js
__What would you like to add/fix?__ 
Expanding border-bottom which is referred in issue #1023 
#1023
=> [jss-plugin-expand]Added the ability to expand the attributes for border-bottom

changelog.md, packages/css-jss/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json, yarn.lock
=> Update css-vendor to 2.0.4

changelog.md, packages/css-jss/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json, yarn.lock
=> Update css-vendor to 2.0.5

changelog.md, packages/css-jss/.size-snapshot.json, packages/jss-plugin-default-unit/.size-snapshot.json, packages/jss-plugin-default-unit/src/defaultUnits.js, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json
Related to https://github.com/mui-org/material-ui/issues/16953. I'm not 100% convinced its the right solution, but it's worth trying.
*I hope you don't mind the created branch, I will delete it after.*
=> Consistent usage of the CSS browser API

packages/css-jss/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json, yarn.lock
=> Update css-vendor to 2.0.6

changelog.md, packages/react-jss/.size-snapshot.json, packages/react-jss/src/utils/getSheetIndex.js
https://github.com/cssinjs/jss/issues/1183
=> Fallback for `Number.MIN_SAFE_INTEGER`

docs/react-jss.md
Typos and wording in the introduction to the react-jss docs
=> Fix: typos

docs/performance.md
Link to comparison repository is not valid anymore.  Modified link URL to existing page.
=> Update comparison link

changelog.md, docs/performance.md, packages/css-jss/.size-snapshot.json, packages/jss-plugin-nested/.size-snapshot.json, packages/jss-plugin-nested/src/index.js, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/jss/.size-snapshot.json, packages/jss/src/Jss.js, packages/jss/src/RuleList.js, packages/jss/src/StyleSheet.js, packages/jss/src/plugins/conditionalRule.js, packages/jss/src/types/jss.js, packages/jss/tests/integration/sheet.js, packages/react-jss/.size-snapshot.json, packages/react-jss/src/JssProvider.test.js, packages/react-jss/src/styled-props-filter.test.js, packages/react-jss/src/styled.test.js, packages/react-jss/src/utils/sheets.js, packages/react-jss/src/utils/sheetsMeta.js, packages/react-jss/test-utils/createDynamicStylesTests.js, packages/react-jss/tests/styledSystem.js
=> Updating styles a list item which has a nested rule

packages/css-jss/src/index.d.ts
#1246 
Add typescript types for css-jss package
=> Add TS types for css-jss packages

packages/react-jss/src/index.d.ts
=> Revert type change

.github/ISSUE_TEMPLATE/---bug-report.md
:writing_hand: **Fix typo in jss repo**
**File that have typo**
```
jss/.github/ISSUE_TEMPLATE/---bug-report.md:11:40: "happend" is a misspelling of "happened"
```
**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart: 
Making the world a better place :innocent:
=> Fix typo in jss repo

docs/projects.md
=> DOC: Updated the URL Links

docs/users.md
- [x ] Add tests if possible
- [x ] Add changelog if users should know about the change
- [x ] Add documentation
=> Add SwissDev Jobs as a user

changelog.md, packages/css-jss/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/.size-snapshot.json, packages/jss-plugin-vendor-prefixer/package.json, packages/jss-preset-default/.size-snapshot.json, packages/jss-starter-kit/.size-snapshot.json, packages/react-jss/.size-snapshot.json, yarn.lock
=> Update css-vendor to 2.0.8

packages/jss/src/index.d.ts
fix issue https://github.com/cssinjs/jss/issues/1366
=> fix StyleSheet declare issue

packages/react-jss/package.json, yarn.lock
N/A
Update the theming dependency to ^3.2.1 - the only change is https://github.com/cssinjs/theming/pull/93
=> bump theming to ^3.2.1

packages/jss-plugin-default-unit/src/defaultUnits.js, packages/jss-plugin-default-unit/src/index.test.js
Closes #1414
#1414
Add default units to logical properties
=> Add default units to logical properties

changelog.md, packages/jss/.size-snapshot.json, packages/jss/src/DomRenderer.js, packages/jss/src/StyleSheet.js, packages/jss/tests/functional/sheet.js
=> Delete rule perf

packages/jss/.size-snapshot.json, packages/jss/src/utils/toCss.js
We have unnecessary template literals
=> remove unnecessary template literal

packages/jss-plugin-cache/.size-snapshot.json, packages/jss-plugin-cache/src/index.js, packages/jss-starter-kit/.size-snapshot.json
=> use .has instead of .get

packages/react-jss/package.json
I changed `react` to `>=16.8.6` becuase `react-dom` is `16.8.6`
=> Fix react peer dep version corresponding react-dom

packages/jss/src/index.d.ts
=> types: improve Styles types, allow arrays  https://github.com/cssinjs/jss/issues/1422

packages/react-jss/.size-snapshot.json, packages/react-jss/src/JssProvider.js
All local test passed
All flow check passed
https://github.com/cssinjs/jss/issues/1506
=> JssProvider: convert class component to function component

packages/react-jss/.size-snapshot.json, packages/react-jss/src/withStyles.js
@kof I did but I need your help,
Items:
- Flow announcements 
- 2  Tests failed
`should render a number of composed style rules with withStyles API`
`allows nested ThemeProviders with custom namespace`
SUMMARY of Test:
`713 tests completed`
`12 tests skipped`
`2 tests failed`
=> Refactor withStyles

packages/react-jss/.size-snapshot.json, packages/react-jss/src/utils/getSheetClasses.js
We declare a variable that is not used in some cases so I changed the order
=> fix(react-jss): fix order of definition variable

docs/projects.md
https://github.com/cssinjs/jss/discussions/1558
=> Add Linters

docs/react-jss.md
This is just a mistake in `react-jss` docs
=> docs(react-jss): fix a mistake

docs/faq.md
1. Does JSS has overhead? 
1. Does JSS have overhead? 
When the subject of a sentence is a third person (he, she, it) we need to follow the rules of Subject-Verb Agreement. Basically add an s to the end of the verb, but when the verb "do" is used it has priority over the other verb so it always matches the subject. In this case the verb "have" has also been matched by mistake.
=> Line 23 grammar mistake

packages/jss/src/plugins/conditionalRule.js, packages/jss/tests/integration/rules.js
Add support for CSS Container Queries
See more: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries
Added '@container` as a possible match to the RegEx or conditional rule keys.
=> Add support for CSS Container Queries (fixes #1629)
